development:
  host: localhost
  adapter: postgresql
  database: symplify_development

staging:
  adapter: postgresql
  database: symplify_staging

production:
  adapter: postgresql
  database: symplify_production

test:
  host: localhost
  adapter: postgresql
  database: symplify_test